# Uncomment this line to define a global platform for your project

platform :ios, '9.2'
use_frameworks!

target 'Coffee Mapper' do
pod 'HCSStarRatingView', '~> 1.4.4'
pod 'Firebase', '~> 2.5.0'
pod 'QuadratTouch', '>= 1.0'
pod 'RealmSwift'
end